<a href="https://colab.research.google.com/github/shimaaahmedd/Puzzle/blob/main/Puzzle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import queue 
import time

In [ ]:
goal = np.zeros((3,3))
for i in range(3):
  for j in range(3):
   goal[i][j] = input("Enter number in place row {} and column {} of goal Matrix: ".format(i,j))
goal = goal.astype(int)
print( "The Goal Matrix: \n {}".format(goal))

Enter number in place row 0 and column 0 of goal Matrix: 0
Enter number in place row 0 and column 1 of goal Matrix: 1
Enter number in place row 0 and column 2 of goal Matrix: 2
Enter number in place row 1 and column 0 of goal Matrix: 3
Enter number in place row 1 and column 1 of goal Matrix: 4
Enter number in place row 1 and column 2 of goal Matrix: 5
Enter number in place row 2 and column 0 of goal Matrix: 6
Enter number in place row 2 and column 1 of goal Matrix: 7
Enter number in place row 2 and column 2 of goal Matrix: 8
The Goal Matrix: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
puzzle = np.zeros((3,3))
for i in range(3):
  for j in range(3):
    puzzle[i][j] = input("Enter number in place row {} and column {} of inital state puzzle: ".format(i,j))

puzzle = puzzle.astype(int)
print( "The Initial State Puzzle: \n {}".format(puzzle))

Enter number in place row 0 and column 0 of inital state puzzle: 0
Enter number in place row 0 and column 1 of inital state puzzle: 8
Enter number in place row 0 and column 2 of inital state puzzle: 7
Enter number in place row 1 and column 0 of inital state puzzle: 6
Enter number in place row 1 and column 1 of inital state puzzle: 5
Enter number in place row 1 and column 2 of inital state puzzle: 4
Enter number in place row 2 and column 0 of inital state puzzle: 3
Enter number in place row 2 and column 1 of inital state puzzle: 2
Enter number in place row 2 and column 2 of inital state puzzle: 1
The Initial State Puzzle: 
 [[0 8 7]
 [6 5 4]
 [3 2 1]]


# **A* Informed Search**

In [ ]:
def find_empty(puzzle):
  empty_tile = np.where(puzzle == 0)
  return empty_tile

In [ ]:
def neighbor(empty_tile, puzzle):
  neighbors = []
  empty_tile = find_empty(puzzle)
  i = empty_tile[0]
  j = empty_tile[1]
  if i-1 >= 0:
    neighbors.append([i - 1, j])
  if i+1 <= 2:
    neighbors.append([i + 1, j])
  if j-1 >= 0:
    neighbors.append([i, j-1])
  if j+1 <= 2:
    neighbors.append([i, j+1])
  return neighbors


In [ ]:
def heuristic(goal, puzzle):
  count=0
  for i in range(3):
    for j in range(3):
      if puzzle[i][j]!=0:
        goal_index = np.where(goal == puzzle[i][j])         
        if goal_index[0] - i != 0 or goal_index[1] - j != 0:
          count+=1
  return count

In [ ]:
def graph(coordinates_neighbor_result, puzzle, g, goal, empty_tile, visited,F_list,ind):
  index_Array=[]
  List=[]
  h_list=[]
  h=0
  
  if any(np.array_equal(puzzle, i) for i in visited) == False:
      visited.append(np.array(puzzle))
      if len(F_List):
          F_List.pop(0)
          for k in coordinates_neighbor:
              temp = puzzle.copy()
              temp[k], temp[empty_tile]  = temp[empty_tile], temp[k]
              if any(np.array_equal(temp, i) for i in visited) == False:
                h = heuristic(goal, temp)
                f = g + h
                F_List.append((f,ind))
                h_list.append(h)
                index_Array.append(np.array(temp))
                ind=ind+1
      else:
        print("- This Puzzle is Not Solvable") 

  F_List.sort()
  
  if len(F_List):
    List=F_List.pop(0)
    h= h_list.pop(List[1])
    List= index_Array.pop(List[1])
    ind=ind-1
    print(List)
  return g, List, visited , h

In [ ]:
g = 0
k = 0
f=0
ind=0
F_List =[]
visited = []
result_puzzle = puzzle.copy()
t0 = time.time()
h=heuristic(goal,result_puzzle)
f=h+g
F_List.append(result_puzzle)
print("The Path to the Goal:\n ")
while h != 0:
  empty_tile = find_empty(result_puzzle)
  coordinates_neighbor = neighbor(empty_tile, result_puzzle)
  g, result, visited , h = graph(coordinates_neighbor, result_puzzle, g, goal, empty_tile, visited, F_List,ind)
  result_puzzle = result
  g +=1
t1 = time.time() - t0
print("The Expanded Nodes: \n") 
print(visited)
print("Running time of A* Informed Search = ", t1, " seconds")
print("The Cost of The Path :{}".format(g))

The Path to the Goal:
 
[[6 8 7]
 [0 5 4]
 [3 2 1]]
[[6 8 7]
 [3 5 4]
 [0 2 1]]
[[6 8 7]
 [3 5 4]
 [2 0 1]]
- This Puzzle is Not Solvable
The Expanded Nodes: 

[array([[0, 8, 7],
       [6, 5, 4],
       [3, 2, 1]]), array([[6, 8, 7],
       [0, 5, 4],
       [3, 2, 1]]), array([[6, 8, 7],
       [3, 5, 4],
       [0, 2, 1]]), array([[6, 8, 7],
       [3, 5, 4],
       [2, 0, 1]])]
Running time of A* Informed Search =  0.006923675537109375  seconds
The Cost of The Path :4


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:14: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  


# **BFS**

In [ ]:
GoalState = list(goal.flatten())

start_state= list()
GoalNode = None 

NodesExpanded = 0 
MaxSearchDeep = 0 
MaxFrontier = 0 

In [ ]:
## class for the graph node for traversal
class Node:
	def __init__( self, state, parent, operator, depth, cost ):
		# Contains the state of the node, [list of the state of the board at this node]
		self.state = state
		# Contains the node that generated this node
		self.parent = parent
		# Contains the operation that generated this node from the parent
		self.operator = operator
		# Contains the depth of this node (parent.depth +1)
		self.depth = depth
		# Contains the path cost of this node from depth 0. Not used for depth/breadth first.
		self.cost = cost
		if self.state:
			self.map = ''.join(str(e) for e in self.state)

In [ ]:
##function used to move the blank tile
def move(state, idx):
	new_state = state[:]
	index = new_state.index( 0 )

	#Moves the blank tile up on the board. 
	if idx == 0:
		if index not in range(0, board_side):
			new_state[index - board_side], new_state[index] = new_state[index],new_state[index - board_side]
			return new_state
		else:
			return None

	#Moves the blank tile Down on the board.     
	elif idx == 1:
		if index not in range(board_len - board_side, board_len):
			new_state[index + board_side], new_state[index] = new_state[index] , new_state[index + board_side]
			return new_state
		else:
			return None

	#Moves the blank tile left on the board.
	elif idx == 2:
		if index not in range(0, board_len, board_side):
			new_state[index - 1], new_state[index] = new_state[index], new_state[index - 1]
			return new_state
		else:
			return None

	#Moves the blank tile right on the board
	elif idx == 3:
		if index not in range(board_side - 1, board_len, board_side):
			new_state[index + 1] , new_state[index] = new_state[index],new_state[index + 1]
			return new_state
		else:
			return None

In [ ]:
## function used to create new node
def create_node( state, parent, operator, depth, cost ):
	return Node( state, parent, operator, depth, cost )

## function used to expand nodes
def expand_node( node ):
	"""Returns a list of expanded nodes"""

	expanded_nodes = []

	expanded_nodes.append( create_node( move( node.state , 0 ), node, "u", node.depth + 1, node.cost + 1 ) )
	expanded_nodes.append( create_node( move( node.state , 1 ), node, "d", node.depth + 1, node.cost + 1  ) )
	expanded_nodes.append( create_node( move( node.state , 2 ), node, "l", node.depth + 1, node.cost + 1 ) )
	expanded_nodes.append( create_node( move( node.state , 3 ), node, "r", node.depth + 1, node.cost + 1  ) )

	# Filter the list and remove the nodes that are impossible (move function returned None)
	filteredNodes = [node for node in expanded_nodes if node.state != None]
	return filteredNodes

In [ ]:
def bfs(startState):
	global MaxFrontier, GoalNode, MaxSearchDeep

	boardVisited = set()
	queue = list([create_node(startState, None, None, 0, 0)])

	while queue:
		node = queue.pop(0)
		boardVisited.add(node.map)

		if node.state == GoalState:
			GoalNode = node
			return queue, boardVisited

		posiblePaths = expand_node(node)
		for path in posiblePaths:
			if path.map not in boardVisited:
				queue.append(path)
				boardVisited.add(path.map)
	return None, None

In [ ]:
def setStartState(start):
	global start_state
	start_state = start

In [ ]:
global board_len
setStartState(list(puzzle.flatten()))
board_len = len(start_state)
global board_side
board_side= int(board_len ** 0.5)
t0 = time.time()
result, explored = bfs(start_state)
t1 = time.time() - t0
global moves
if result == None:
  print ("No solution found")
  moves = None
elif result == [None]:
  print ("Start node was the goal!")
  moves = [None]
else:
  print("Solution Found")
  moves = []
  path = []
  p = GoalNode
  cost = p.cost
  search_depth = p.depth
  while p.operator != None:
    moves.append(p.operator)
    path.append(p.state)
    p = p.parent
  path.reverse()
  print("cost to the goal= \n",cost)
  print("path to the goal:\n",path)
  print("The search depth:\n",search_depth)
  print("expanded nodes: \n",explored)
  print("number of expanded nodes:\n",len(explored))
  print("Running time = ", t1, " seconds")

Solution Found
cost to the goal= 
 3
path to the goal:
 [[1, 2, 0, 3, 4, 5, 6, 7, 8], [1, 0, 2, 3, 4, 5, 6, 7, 8], [0, 1, 2, 3, 4, 5, 6, 7, 8]]
The search depth:
 3
expanded nodes: 
 {'125304678', '142350678', '125348670', '125034678', '125348607', '125374068', '142305678', '025134678', '125340678', '125374608', '102345678', '125374680', '125308647', '015324678', '125634078', '142035678', '012345678', '105324678', '142375608', '150324678', '120345678', '125348067'}
number of expanded nodes:
 22
Running time =  0.0004494190216064453  seconds


#**DFS**

In [ ]:
GoalState = list(goal.flatten())
# start_state= list()
GoalNode = None

NodesExpanded = 0
MaxSearchDeep = 0
MaxFrontier = 0

In [ ]:
## Node class used for the traversal
class Node:
    def __init__(self, state, parent, operator, depth, cost):
        # Contains the state of the node, [list of the state of the board at this node]
        self.state = state
        # Contains the node that generated this node
        self.parent = parent
        # Contains the operation that generated this node from the parent
        self.operator = operator
        # Contains the depth of this node (parent.depth +1)
        self.depth = depth
        # Contains the path cost of this node from depth 0. Not used for depth/breadth first.
        self.cost = cost
        if self.state:
            self.map = ''.join(str(e) for e in self.state)

In [ ]:
## function used to move the blank tile
def move(state, idx):
    new_state = state[:]
    index = new_state.index(0)

    # Moves the blank tile up on the board.
    if idx == 0:
        if index not in range(0, board_side):
            new_state[index - board_side], new_state[index] = new_state[index], new_state[index - board_side]
            return new_state
        else:
            return None

    # Moves the blank tile Down on the board.
    elif idx == 1:
        if index not in range(board_len - board_side, board_len):
            new_state[index + board_side], new_state[index] = new_state[index], new_state[index + board_side]
            return new_state
        else:
            return None

    # Moves the blank tile left on the board.
    elif idx == 2:
        if index not in range(0, board_len, board_side):
            new_state[index - 1], new_state[index] = new_state[index], new_state[index - 1]
            return new_state
        else:
            return None

    # Moves the blank tile right on the board
    elif idx == 3:
        if index not in range(board_side - 1, board_len, board_side):
            new_state[index + 1], new_state[index] = new_state[index], new_state[index + 1]
            return new_state
        else:
            return None


In [ ]:
## function used to create node
def create_node(state, parent, operator, depth, cost):
    return Node(state, parent, operator, depth, cost)

## function used to expand graph node
def expand_node(node):
    """Returns a list of expanded nodes"""

    expanded_nodes = []

    expanded_nodes.append(create_node(move(node.state, 0), node, "u", node.depth + 1, node.cost + 1 ))
    expanded_nodes.append(create_node(move(node.state, 1), node, "d", node.depth + 1, node.cost + 1 ))
    expanded_nodes.append(create_node(move(node.state, 2), node, "l", node.depth + 1, node.cost + 1 ))
    expanded_nodes.append(create_node(move(node.state, 3), node, "r", node.depth + 1, node.cost + 1 ))

    # Filter the list and remove the nodes that are impossible (move function returned None)
    filteredNodes = [node for node in expanded_nodes if node.state != None]
    return filteredNodes

In [ ]:
## main function for the dfs traversal
def dfs(startState):
    global MaxFrontier, GoalNode, MaxSearchDeep
    global max_depth
    max_depth = 0
    boardVisited = set()
    stack = list([create_node(startState, None, None, 0, 0)])

    while stack:
        node = stack.pop()
        if node.depth > max_depth:
            max_depth = node.depth
        boardVisited.add(node.map)

        if node.state == GoalState:
            GoalNode = node
            return stack, boardVisited

        posiblePaths = reversed(expand_node(node))
        for path in posiblePaths:
            if path.map not in boardVisited:
                stack.append(path)
                boardVisited.add(path.map)
    return None,None

In [ ]:
def setStartState(start):
    global start_state
    start_state = start

In [ ]:
  global board_len
  setStartState(list(puzzle.flatten()))
  board_len = len(start_state)
  global board_side
  board_side = int(board_len ** 0.5)
  global moves

  t0 = time.time()
  result, explored = dfs(start_state)
  t1 = time.time()  -t0
  if result == None:
      print("No solution found")
      moves = None

  elif result == [None]:
      print("Start node was the goal!")
      moves = [None]
  else:
      print("Solution Found")
      moves = []
      path = []
      p = GoalNode
      cost = p.cost
      while p.operator != None:
          moves.append(p.operator)
          path.append(p.state)
          p = p.parent
      path.reverse()
      print("cost to the goal= \n", cost)
      print("path to the goal:\n", path)
      print("The search depth:\n", max_depth)
      print("number of expanded nodes:\n", len(explored))
      print("Running time = ", t1, " seconds")

Solution Found
cost to the goal= 
 1
path to the goal:
 [[0, 1, 2, 3, 4, 5, 6, 7, 8]]
The search depth:
 1
number of expanded nodes:
 4
Running time =  0.0001590251922607422  seconds
